name: Branch v8.0 - Windows - EssentialCSharp

on:
  push:
    branches: [ v8.0 ]
  pull_request:
    branches: [ v8.0 ]
  schedule:
    - cron: 0 6 * * 1

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Get Build Information
      run: |
        pwd
        dotnet --info
        dotnet --version
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal